### ISSUE TITLE
Outlaw update - version 3.85

### ISSUE THREAD

**Issue by louanfontenele** [goatfungus/NMSSaveEditor#534] opened 2022-04-13 13:16 UTC
Please update to the new version.
Thanks

**Comment by m0lz** [comment] 2022-04-13 21:29
To help out, here's a few name mappings not found with NMS SaveEditor 1.9.10 used on a save from NMS 3.85 ..

Reading metadata for save4.hg
  Version: 589830
  TotalPlayTime: 16:00
  using name mappings: NMS 3.8
  WARNING: name mapping not found: fkY
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - NORMAL - Apr 13, 22:18
  Filename: save.hg
  using name mappings: NMS 3.8
  WARNING: name mapping not found: 7?0
  WARNING: name mapping not found: S5O
  WARNING: name mapping not found: >r:
  WARNING: name mapping not found: :dY
  WARNING: name mapping not found: yDG
  WARNING: name mapping not found: sti
  WARNING: name mapping not found: Pqk

**Comment by JB2021-81** [comment] 2022-04-14 04:26
I'm looking forward to this editor & Cheat Happens updating. I use both to make NMS my own 😂
O(∩_∩)O

**Comment by NetZero** [comment] 2022-04-14 11:48
Some might related to wingman features:
7?0 wingman slot, true if unlocked
S5O wingman stats general
>r: wingman NPC race
:dY wingman starship model

**Comment by Qluzzz** [comment] 2022-04-14 21:56
Well a new expedition dropped today also. So it would be nice to get both at the same time!! Good Job

**Comment by JB2021-81** [comment] 2022-04-14 22:14
After playing the game for most of the day, I really can't wait for this save editor to get updated, there's so much I want to change in my savegame, like get a new solar ship, etc., no need to rush it, I'll wait.

**Comment by JB2021-81** [comment] 2022-04-14 23:54
I just got one of the solar ships, get a system conflict scanner look for Pirate Controlled systems, then wait in the derelict space station for a solar ship to arrive, took me 30 seconds. (I'm in the expedition, so I'd really like to upgrade some things w/ this editor for sure.. lol.

**Comment by Spirit-Warden** [comment] 2022-04-15 00:31
While I'm also hoping the save editor is updated soon, so I can add those expedition rewards. I have a question, can the save editor be used to unlocked cosmetics too? There's that new Freedom Hood thing I really want to use.

**Comment by JB2021-81** [comment] 2022-04-15 05:02
> While I'm also hoping the save editor is updated soon, so I can add those expedition rewards. I have a question, can the save editor be used to unlocked cosmetics too? There's that new Freedom Hood thing I really want to use.

The hood would be awesome to unlock in the editor, but is it that hard to get in the expedition?

**Comment by DarkPulse** [comment] 2022-04-16 01:06
Expedition stuff can't really be done via the save editor.

Sure, you can add it to your inventory, but the game will also check with the servers if you unlocked it. IIRC if you did not unlock it, it will simply delete the items from the inventory.

The only way to prevent this is to disable all online functionality for the game and block it via your firewall and the like... at which point you've basically killed off a lot of game content.

Just play the expedition. You get five weeks to complete them, and once you remotely know what you're doing, you can knock them out in about 10-15 hours.

**Comment by jc1011101** [comment] 2022-04-16 03:38
> Expedition stuff can't really be done via the save editor.
> 
> Sure, you can add it to your inventory, but the game will also check with the servers if you unlocked it. IIRC if you did not unlock it, it will simply delete the items from the inventory.
> 
> The only way to prevent this is to disable all online functionality for the game and block it via your firewall and the like... at which point you've basically killed off a lot of game content.
> 
> Just play the expedition. You get five weeks to complete them, and once you remotely know what you're doing, you can knock them out in about 10-15 hours.

What?  They don't delete the rewards from your save file or inventory. I don't know where you came up with that. You can unlock all rewards from all previous expeditions and the twitch rewards through this save editor all while being online. Also you can use the content across all your save files.

I do agree that they are easy and can be easily done in a few hours.

**Comment by DarkPulse** [comment] 2022-04-16 05:04
> What? They don't delete the rewards from your save file or inventory. I don't know where you came up with that. You can unlock all rewards from all previous expeditions and the twitch rewards through this save editor all while being online. Also you can use the content across all your save files.
> 
> I do agree that they are easy and can be easily done in a few hours.

Maybe it's Twitch rewards then. I dunno, I just remember hearing some limited items had a server check, and so trying to cheat them would not work.

**Comment by alxxxx** [comment] 2022-04-16 10:07
> > What? They don't delete the rewards from your save file or inventory. I don't know where you came up with that. You can unlock all rewards from all previous expeditions and the twitch rewards through this save editor all while being online. Also you can use the content across all your save files.
> > I do agree that they are easy and can be easily done in a few hours.
> 
> Maybe it's Twitch rewards then. I dunno, I just remember hearing some limited items had a server check, and so trying to cheat them would not work.

In order to get items from expeditions, you need to turn off the network.
But after you have taken the items from the NPC, you can turn on the network and nothing is lost!!!

**Comment by themunchkinman** [comment] 2022-04-17 00:17
@goatfungus - Is there anything non-coders can do to assist (besides being patient and reasonable with expectations)? 

Love the work, it's a life-saver. My only alternative was to write-in my own narrative that you may at times be forced to jump dimensions and lose something you love forever.

**Comment by AnalyticalBear** [comment] 2022-04-17 02:16
@goatfungus If there's anything even coders can do I'm willing to help out.
I've worked in Java web applications but if there's any non-development task, or development, I'm willing to help.

**Comment by KiARC** [comment] 2022-04-17 13:02
> Expedition stuff can't really be done via the save editor.
> 
> Sure, you can add it to your inventory, but the game will also check with the servers if you unlocked it. IIRC if you did not unlock it, it will simply delete the items from the inventory.
> 
> The only way to prevent this is to disable all online functionality for the game and block it via your firewall and the like... at which point you've basically killed off a lot of game content.
> 
> Just play the expedition. You get five weeks to complete them, and once you remotely know what you're doing, you can knock them out in about 10-15 hours.

As long as you aren't scared of JSON, open he raw JSON editor for your Expedition save, then go to PlayerStateData -> SeasonState -> MilestoneValues and bump every value in the array up to an arbitrarily large number (it has to be higher than the highest needed for any of them, like "10,000 steps" means 10000 is the max so go with 329853 or something, doesn't really matter all that much just make it big). Then save that, load your save, and redeem everything. It should work, it's worked on every expedition so far for me. The server validates that you've *redeemed* milestones. The client validates progress.

**Comment by STRUCTUR3** [comment] 2022-04-17 16:54
> > Expedition stuff can't really be done via the save editor.
> > Sure, you can add it to your inventory, but the game will also check with the servers if you unlocked it. IIRC if you did not unlock it, it will simply delete the items from the inventory.
> > The only way to prevent this is to disable all online functionality for the game and block it via your firewall and the like... at which point you've basically killed off a lot of game content.
> > Just play the expedition. You get five weeks to complete them, and once you remotely know what you're doing, you can knock them out in about 10-15 hours.
> 
> As long as you aren't scared of JSON, open the raw JSON editor for your Expedition save, then go to PlayerStateData -> SeasonState -> MilestoneValues and bump every value in the array up to an arbitrarily large number (it has to be higher than the highest needed for any of them, like "10,000 steps" means 10000 is the max so go with 329853 or something, doesn't really matter all that much just make it big). Then save that, load your save, and redeem everything. It should work, it's worked on every expedition so far for me. The server validates that you've _redeemed_ milestones. The client validates progress.

How did you do this? I've tried to do this before and couldn't figure out where to use the JSON editor.

**Comment by STRUCTUR3** [comment] 2022-04-17 17:02
> > Expedition stuff can't really be done via the save editor.
> > Sure, you can add it to your inventory, but the game will also check with the servers if you unlocked it. IIRC if you did not unlock it, it will simply delete the items from the inventory.
> > The only way to prevent this is to disable all online functionality for the game and block it via your firewall and the like... at which point you've basically killed off a lot of game content.
> > Just play the expedition. You get five weeks to complete them, and once you remotely know what you're doing, you can knock them out in about 10-15 hours.
> 
> As long as you aren't scared of JSON, open the raw JSON editor for your Expedition save, then go to PlayerStateData -> SeasonState -> MilestoneValues and bump every value in the array up to an arbitrarily large number (it has to be higher than the highest needed for any of them, like "10,000 steps" means 10000 is the max so go with 329853 or something, doesn't really matter all that much just make it big). Then save that, load your save, and redeem everything. It should work, it's worked on every expedition so far for me. The server validates that you've _redeemed_ milestones. The client validates progress.

Where did you find the values? I just see a bunch of numbers and "?"s.

**Comment by Fevix** [comment] 2022-04-17 20:55
> Maybe it's Twitch rewards then. I dunno, I just remember hearing some limited items had a server check, and so trying to cheat them would not work.

Twitch does use server validation, and Twitch's servers store your Twitch Inventory. 

If you completely disable your internet connection before launching the game, though, you can bypass that, because the game DOES store a local copy that this save editor can modify to allow you to redeem rewards you don't qualify for.

Once you've redeemed them, you can turn your internet connection back on, and on next launch NMS will re-download your Twitch claims. It doesn't delete anything, it only removes the items from the list of claimables. 

There's not much Twitch offers that you can't otherwise get. An A-rank of the 4 original classes (Shuttle, freighter, explorer, and two fighters), which you can already earn ingame and don't come with any special modules or anything, some decorative items, and some pets. It's not like the Normandy from the Beachhead expedition where it's something that can't otherwise be gained.

**Comment by realrobd** [comment] 2022-04-18 13:20
Please update soon <3

**Comment by JB2021-81** [comment] 2022-04-18 19:44
> Please update soon <3

Stop asking for him to update it soon, it will get done when it gets done.

**Comment by realrobd** [comment] 2022-04-18 19:50
> > Please update soon <3
> 
> Stop asking for him to update it soon, it will get done when it gets done.

Who are you?
Don't tell me what to do, ya knob.

**Comment by AnnQuark** [comment] 2022-04-18 19:51
Hello!

First of all, this tool is awesome, particularly the Java version, you can run it on any OS with a java environment - well it works superfine on GNU\Linux, I haven't tried it on FreeBSD but I suppose it also works because, naturally, java applications work on Unices. Well, I would have tried if only Steam would work on FreeBSD (and I have tried hard, believe me, this is the reason I use GNU\Linux as a playing platform with a pseudo dual boot (yeah my EFI is my bootloader, LOL, but this is because of BSD).

I have just one request : would it be possible to add into the list of the known objects the pirate map fragments ? The issue is that if your character die during the mile stone where you need to find the first map fragment, you never get it and you have to restart the expedition (well, I've already finished the three first stages).

I think that the IDs of these object are :
^PIRATE_MAPPROD0
^PIRATE_MAPPROD1
^PIRATE_MAPPROD2
^PIRATE_MAPWHOLE

Well, I'm pretty sure of that, because I can see the three last ones in the editor for I have got them in my inventory ingame, as I have completed the missions. But it's impossible to add them through the editor yet.

Concerning myself, I think that I'll restart the game if it's not possible, considering it may not be worth, the expeditions don't last forever.

I apologize for my English, this is not my mother language. ;)

Nice Easter eve to everybody!

**Comment by goatfungus** [comment] 2022-04-18 22:33
Hi All,

New version has been uploaded today with support for most of the new stuff added in Outlaws:

- Cargo inventory for ships
- Solar ship type
- Additional items / twitch rewards / etc

I still need to figure out the wingman structures and how they work in the game, so please be patient on that one. Also, the name mappings have not been completed, but that shouldn't affect you using the editor.

**Comment by goatfungus** [comment] 2022-04-18 22:46
With regards to Solar ships, as far as I can tell, there is a new technology that is required for them to work: "Vesper Sail"... you should be able to change a standard ship type to Solar and add the technology, and you'll be good to go.

**Comment by Spirit-Warden** [comment] 2022-04-18 23:51
> Hi All,
> 
> New version has been uploaded today with support for most of the new stuff added in Outlaws:
> 
>     * Cargo inventory for ships
> 
>     * Solar ship type
> 
>     * Additional items / twitch rewards / etc
> 
> 
> I still need to figure out the wingman structures and how they work in the game, so please be patient on that one. Also, the name mappings have not been completed, but that shouldn't affect you using the editor.

How does one unlock the Shroud of Freedom and Lost Bathysphere using the save editor? Cheers :)

**Comment by AnnQuark** [comment] 2022-04-19 09:31
Hello!

That's very good news, I'll try it today. Thank you for this work, because it's awesome.

**Comment by themunchkinman** [comment] 2022-04-19 13:53
> Hi All,
> 
> New version has been uploaded today with support for most of the new stuff added in Outlaws:
> 
>     * Cargo inventory for ships
>     * Solar ship type
>     * Additional items / twitch rewards / etc
> > 
> I still need to figure out the wingman structures and how they work in the game, so please be patient on that one. Also, the name mappings have not been completed, but that shouldn't affect you using the editor.

Thank you so much. I think patience is the least we can do. For now, are the following warnings currently expected in 3.87 (patch released earlier today)?
```
WARNING: name mapping not found: 7?0
WARNING: name mapping not found: S5O
WARNING: name mapping not found: >r:
WARNING: name mapping not found: :dY
WARNING: name mapping not found: yDG
WARNING: name mapping not found: sti
WARNING: name mapping not found: Pqk
```

**Comment by AnnQuark** [comment] 2022-04-19 14:21
Hello again!

I haven't tried to unlock ships yet, but the unlocking of objects and recipes works fine, as far as I've tried.

**Comment by scard15angel** [comment] 2022-04-19 16:24
It takes time to update the code, he has a life outside of the save editor, that being said, I am sure he is working hard to get the save editor to play nice with the new outlaws update. But if we rush him. We could end up with a save editor that corrupts our files and destroys our beautiful hard earned (or cheated in I don't judge) ships. Let him work this out in his own time. Otherwise we will reap the consequences.

**Comment by goatfungus** [comment] 2022-04-19 21:46
> For now, are the following warnings currently expected in 3.87 (patch released earlier today)?
> 
> ```
> WARNING: name mapping not found: fkY
> ...
> WARNING: name mapping not found: 7?0
> WARNING: name mapping not found: S5O
> WARNING: name mapping not found: >r:
> WARNING: name mapping not found: :dY
> WARNING: name mapping not found: yDG
> WARNING: name mapping not found: sti
> WARNING: name mapping not found: Pqk
> ```

Yes. Warnings are fine, it just means we won't be able to edit those parts of the save file.

**Comment by Devilin-Pixy** [comment] 2022-04-20 02:30
Here are some of the mappings, just a few missing:

```
fkY > SpaceCombatFollowMode
7?0 >
S5O >
>r: >
:dY >
?=t > Options
jN4 > Layer
xIx > OverrideColour
DE0 > OptionName
sti > TrashInventoryOnGalaxyTravel
pqK > FreighterBattleEarlyWarpsOverride

```

**Comment by goatfungus** [comment] 2022-04-20 04:38
@Devilin-Pixy just out of interest, where do you get the mappings from whenever a game update happens?

**Comment by Devilin-Pixy** [comment] 2022-04-20 13:10
@goatfungus 
Sometimes I get them from decompiled files by comparison:
```
\METADATA\GAMESTATE\... (save files)
\METADATA\ENGINESETTINGS\GCUSERSETTINGSDATA.MBIN (AccountData)
```
Other times I get them from the mappings provided with MBINCompiler once updated.
<https://github.com/monkeyman192/MBINCompiler/releases>

This time I did a mix, to get a few more, as MBINC is not fully updated.
Those missing, I am just unable to get, as not all files decompile just yet

**Comment by goatfungus** [comment] 2022-04-20 23:50
Thanks @Devilin-Pixy.
I have managed to come up with another workaround by reading all the string values in the EXE file and matching the hash value with the mappings in the save file. This seems to work pretty well. I then just compare the result with MBINCompiler when they complete their work.

Anyway, I've just released a new version which should have all the mappings now. If there are any issues, please raise another ticket and I'll close this one now.

**Closed by goatfungus** 2022-04-20 23:50 UTC
