### ISSUE TITLE
Can't load latest save. Showing Slot as "Empty" vs "Normal".

### ISSUE THREAD

**Issue by Zeoran** [goatfungus/NMSSaveEditor#112] opened 2018-08-25 05:21 UTC
I've been using the editor quite a bit in both of my save files, one was an old save from the beginning of NMS, the other was created new post NEXT.  It's been working fine until today.  I downloaded the latest copy of the editor as it asked, unzipped and launched like normal. It auto-found the save file location like normal, I clicked on it and usually I see two options, Slot 1 (Normal) and Slot 2 (Normal), but this time I only saw Slot 1 (Normal) and Slot 2 was marked "(Empty)" and I couldn't load it.  Thing is, slot 1 is my original NMS file and I haven't been using it.  So all my work and all my ships, bases, etc. are all in the second file.  I tried deleting and re-creating the autosave and manual save, no change. I tried exiting the game, no change. I tried deleting the slot 1 save entirely and still no change.  Any help???
![nmseditor](https://user-images.githubusercontent.com/42689745/44615313-1585a280-a7ec-11e8-9e5e-0a0e9e0dfd72.jpg)

**Comment by goatfungus** [comment] 2018-08-25 05:39
See issue #111.
The version unknown message showing in your console indicates you are using the experimental branch of the game, which currently will not work with the editor. I'm going to close this as it is a duplicate.

**Closed by goatfungus** 2018-08-25 05:39 UTC
Labels: duplicate

**Comment by Zeoran** [comment] 2018-08-25 06:55
That sucks. I've been using the experimental branch for a while now. But if it means I lose the editor, it's not worth it.

**Comment by Zeoran** [comment] 2018-08-25 07:03
Well shit.  I tried to go back to non-experimental and the thing actually started me over. It refused to load any of my previous saves. So at this point, there is no going back for me.  And I can't use the editor.  I knew there would be certain "risks" using experimental version, but losing your ENTIRE SAVE FILE wasn't on the list of things I thought I might have to deal with.  Any chance you guys can get the editor t work with the new save game file layout?  Is there anything I can do to help?  I have tons of backups that I've made over the past month.

**Comment by travisnewman** [comment] 2018-08-27 17:36
You didn’t lose your save files but when you started this new version it upgraded them to a point where you can’t go back. 

And what goatfungus was saying was that the editor didn’t work “yet.” 

This happens with new versions sometimes. Structural changes to the save files need app changes. This one more so. 

If you follow the link he sent to the bug this is a duplicate of, you’ll see the progress being made.
