### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by NomisTheElder** [goatfungus/NMSSaveEditor#720] opened 2023-02-12 19:45 UTC
When i run the bat file this pops up in cmd,
'java' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.

And when i run the jar file it pulls up winrar and the save editor doesn't open.
What do i do?

**Comment by NomisTheElder** [comment] 2023-02-12 19:46
I have java 8 installed

**Comment by NomisTheElder** [comment] 2023-02-14 23:19
I figured it out

**Comment by Dr69onS6mur6i** [comment] 2023-02-27 03:49
> I figured it out

by doing....?

**Comment by NomisTheElder** [comment] 2023-02-28 02:55
I had to re-install java 8

**Comment by BraveCaperCat2** [comment] 2023-03-20 17:22
Please close this issue as it is already known you need to have Java 8 and the issue is fixed.

**Closed** 2023-04-06 23:20 UTC
