### ISSUE TITLE
When Changing from Survival to Normal

### ISSUE THREAD

**Issue by Twistedbitt** [goatfungus/NMSSaveEditor#77] opened 2018-08-08 15:42 UTC
I am able to change my save from survival to normal, so i can actually get to a hub where there is potentially more people in it, and when i do this its all fine and dandy until i try to use a spacestation teleport and it just ports me into space itself. Im guessing its because the planet i was on doesnt exsist. is there a way to delete these past portal options?

**Comment by goatfungus** [comment] 2018-08-08 19:46
This is a duplicate of #27 and will be closed for now.

**Closed by goatfungus** 2018-08-08 19:46 UTC
Labels: duplicate
