### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by rtjunkie** [goatfungus/NMSSaveEditor#42] opened 2018-08-01 00:02 UTC
This is actually two suggestions, however one will require some testing, and one should be an easy add. First, the easy one -- I just encountered a game bug unrelated to this editor, however in order to solve my problem, I had to use the JSON editor in the app. Part of my fleet returned from a mission, with 1 damaged ship. I attempted to repair the ship, and all tagged damage points were repaired, however the game insisted that 1 repair point remained, yet it did not exist. As such, I could not complete that repair mission, and could not send that ship back out on a new mission. 

Anyway, moving past the long explanation - an option to repair damaged fleet vehicles would be excellent. It took me a couple tries, but I sorted that the two entries that affected this were easily modified at the following container:

NMS/PlayerStateData/FleetFrigates/[SHIP_NUM]/

The last two entries in that container are: 

"RepairsMade":0,
"DamageTaken":0

When I found these entries, RepairsMade was set to 0, and DamageTaken was set to 65. I first attempted to modify the RepairMade entry to 1, figuring it to be a binary toggle...restarted the game, no fix. I then reset the RepairsMade back to 0, and modified DamageTaken to 0. This did the trick, however I'm still not sure if the RepairsMade entry has some conjoined effect or not. I viewed an undamaged ship to see the default constants set for those entries, and simply mirrored that. When I restarted the game, I had to debrief again, but this time the ship showed no damage on the debrief console like it had before (in red). Following the debrief, the ship was left in its undamaged state, with no mission for repair triggered. 

In the couple tries I made, I noticed that each restart would reset the repair mission completely, however it did not require a repeated debrief since it was just sitting there in limbo. Also even more interesting, the repair mission does NOT get added to the regular mission list! I had encountered a previous game-bug that prevented me from completing a mission, so I edited the JSON that time as well, and was able to change the mission state to allow its completion.  And this leads to the second, more complicated suggestion:

(Force) Complete Mission
Now first, I did not say Force Complete CURRENT Mission, because there are different entries for that, and I was unable to get this to work from those entries. I had to use the master acquired mission list found at NMS/PlayerStateData/MissionProgress/[MISSION_NUM].

This container has all player-acquired missions since the beginning of the game...and the last few sub-containers will be your current missions. I was able to successfully identify the right mission, and was able to change the state of the "Progress":[NUM]. The challenge however is that this is not a binary state, and is an incremental variable. The value is increased by [1] for each completed step in a multi-part mission. I don't know if there is a default "upper limit" that will complete a mission, but it worked with two missions for me, and each had different values - one needed a 6, and another an 8. Also, it set the last state of the mission, and I had to complete it manually in-game...which is actually important considering some end-mission bonuses. 

Anyway, food for thought...I'll try to not take up anymore of your time. Thanks!

-Nate

**Comment by rtjunkie** [comment] 2018-08-01 00:13
Also, I must extend my apologies for failing to offer a sincere thank you for your work on this program! It's been an absolute joy to tinker with my game in a far more advanced way than most "mods". Your efforts are greatly appreciated, especially with the frequency and speed of your updates!

**Comment by goatfungus** [comment] 2018-08-01 02:34
This is probably the most detailed description of a feature request of bug that anyone has sent so far! Well done. Valuable information like this is much appreciated, as it makes my job deciphering it much easier.

Frigate Repairs are coming soon.... I'll probably do exactly what you suggested and set both values to zero. I suspect the "RepairsMade" stat is intended to keep a count of the number of repairs you have made on the frigate in it's currently broken state, so you'd only notice this change if you repaired one item, ran out of resources, and had to travel by ship somewhere else forcing an autosave on landing. The real stat that matters is the "DamageTaken" value.

The mission progress info you gathered is what I thought, but glad to have it confirmed. To implement this fully I will need to pull the names and descriptions of each mission from the game files so it doesn't just show up as ID's in the editor. This is also on the todo list.

Again, thanks for the information. This is good stuff!

**Comment by goatfungus** [comment] 2018-08-01 06:29
I have added the ability to repair damaged frigates in version 1.5.9. They should show up with a little note next to them saying "This frigate is damaged!" and a button to repair.

As for advancing mission progress, since there is already an open issue on this (#36) I'll post any changes there from now on and close this one. Thanks for your feedback.

**Comment by rtjunkie** [comment] 2018-08-02 02:38
Reopening this to keep things together and consistent. 

After writing #50 about Ship deletion behavior, I started thinking about how Frigate Deletion might be operating. I began poking around in the ./PlayerStateData/FleetFrigates container and had a quick revelation. The next container below is ./PlayerStateData/FleetExpeditions, and it hit me that some of the code in that container could create a problem when a Frigate is deleted. The code below is from that second container, and references the ships on active missions. If this record is not checked prior to deletion, it could cause a serious in-game bug when the Mission attempts to continue after the game is launched again.

`"ActiveFrigateIndices":[
		6,
		9,
		8,
		7
	],
	"DamagedFrigateIndices":[],
	"DestroyedFrigateIndices":[],
	"AllFrigateIndices":[
		6,
		7,
		9,
		8
	],`

Also, this directly relates to the original post on this thread, as you'll notice the "DamagedFrigateIndices" and "DestroyedFrigateIndices" entries. The "ActiveFrigateIndices" and "AllFrigateIndices" are enumerated based on the order of selection when the mission primer was being setup, which is why they're not in order in the Indices. 

I think there might need to be a check here to properly complete the Repair Frigate option in the program, so that the Frigate itself is repaired, and the reference to a damaged ship is also removed from the Expedition. 

The best part of this find however, is the "DestroyedFrigateIndices" entry, which might allow us to recover a lost Frigate in the event of a catastrophic mission. Working a Frigate up to S-class and then losing it would be a real pain. I'm pretty sure that both the Repair and the Resurrect options for Frigates would need to take place before a mission is Debriefed. My thoughts are, so long as the debrief has not taken place, then all repair and resurrection actions should be able to take place with complete success.

**Comment by rtjunkie** [comment] 2018-08-02 10:53
Indeed! I figured with as much updating as you do, as well as your attention to other matters, that there would be areas which you may not have discovered or analyzed. Just trying to provide what I can in order to further progress of the program. The more we learn, the better the tool becomes for all of us. :)

**Comment by goatfungus** [comment] 2018-08-03 08:56
I have done a bit of an overhaul of the delete function in version 1.5.10.
Now you cannot delete a frigate that is on a mission.
If you delete a frigate, then all indexes within existing missions are automatically updated to reflect the changes.

No support yet for repairing frigates that are still on a mission but destroyed/damaged, but will look at that later. I just wanted to make sure the editor doesn't break peoples saves.

**Closed by goatfungus** 2018-08-03 08:56 UTC
Labels: enhancement, good first issue

**Comment by rtjunkie** [comment] 2018-08-03 09:10
Excellent work. I've got a completed Expedition right now that has 4 damaged ships that I'm tinkering with. I have yet to turn it in for a debrief, but thus far my manual editing of DamagedFrigateIndices plus the button you made before seems perfect. I've only done this to 1/4 of the ships damaged, but now with the new version I'll see how it behaves for another ship.

**Comment by rtjunkie** [comment] 2018-08-03 09:13
Side-note...Are you on Steam? Would be nice to chat on there to hash out thoughts while tinkering.
