### ISSUE TITLE
Can' press "Reload", "Save Changes" and "Save As"; cant access "Milestones / Reputation"

### ISSUE THREAD

**Issue by NetworkDiskSomething** [goatfungus/NMSSaveEditor#741] opened 2023-03-25 17:34 UTC
Yo, yesterday the program worked fine. I could save the changes and access everything. today I somehow cant save changes anymore for unknown reasons. In addition to that, the secondary Window where all the commands and responds of the program can be seen says : 
[WARNING] name mapping not found: ... like 10 times.

please help

**Comment by GrumpyKoala1966** [comment] 2023-03-25 23:21
Just checked mine and is working as intended.

**Comment by NFKnight** [comment] 2023-04-05 09:29
I've had this issue as well.  It seems inconsistent.  Everything will work fine now and again.

**Comment by goatfungus** [comment] 2023-04-23 22:26
A lot of this should be resolved in the new version.

**Closed by goatfungus** 2023-04-23 22:26 UTC
