### ISSUE TITLE
Multitool Editing

### ISSUE THREAD

**Issue by Blockshaker246** [goatfungus/NMSSaveEditor#771] opened 2023-04-19 16:49 UTC
When ever I try to edit something with my multitool weather it's the class the type of upgrade it's slots or increase its base stats it doesn't save while everything else does. The editor works great just not for multitool. I might just be making conflicting edits

**Comment by goatfungus** [comment] 2023-04-23 01:50
Duplicate of #772

**Closed by goatfungus** 2023-04-23 01:50 UTC
