### ISSUE TITLE
please update the save editor for the Outlaws update

### ISSUE THREAD

**Issue by Zorvalk** [goatfungus/NMSSaveEditor#541] opened 2022-04-18 05:54 UTC
look man i really want to get the rewards for the 6th expedition and im too lazy to do it myself. thats it. thats all i want.

**Comment by dtupper** [comment] 2022-04-18 08:08
Duplicate of #534

**Comment by KiARC** [comment] 2022-04-18 14:42
> look man i really want to get the rewards for the 6th expedition and im too lazy to do it myself. thats it. thats all i want.

I've explained how to do it in #534 and the current version works fine for it.

**Comment by goatfungus** [comment] 2022-04-18 22:37
Look for updates on #534

**Closed by goatfungus** 2022-04-18 22:37 UTC
