### ISSUE TITLE
Base wiring still not backing up properly, please fix!

### ISSUE THREAD

**Issue by biffrapper** [goatfungus/NMSSaveEditor#641] opened 2022-07-31 06:58 UTC
Almost  a year later after reporting this issue it is still not fixed.  The base backup function is broken in that wiring is not saved properly and is about a unit off in position when restored, rendering complex bases with lots of wiring useless.  Please fix.

**Comment by biffrapper** [comment] 2022-07-31 20:26
I believe what is happening is the wiring is being lengthened by 1 unit, thus passing the connection point.

**Comment by biffrapper** [comment] 2022-08-02 05:56
OKAY!  I found where the editor is messing stuff up but I dunno how to code anymore plus I don't have access to the source.  What is happening is as follows, and here is a wiring co-ordinate example...  BOLDED TEXT indicates the discrepancy.

Original co-ordinates:
{
	"Timestamp":1659078490,
	"ObjectID":"^U_PORTALLINE",
	"UserData":0,
	"Position":[
		5.108184814453125,
		69.60919189453125,
		17.330902099609376
	],
	"Up":[
		0.30351680517196658,
		0.44894134998321535,
		-0.8404339551925659
	],
	**"At":[
		2.651535749435425,
		-15.54954719543457,
		-7.348642826080322
	]**
}

Post-backup co-ordinates:
{
	"Timestamp":1659251413,
	"ObjectID":"^U_PORTALLINE",
	"UserData":0,
	"Position":[
		5.108184814453125,
		69.60919189453125,
		17.330902099609376
	],
	"Up":[
		0.30351680517196658,
		0.44894134998321535,
		-0.8404339551925659
	],
	**"At":[
		2.8039073944091799,
		-16.4431095123291,
		-7.770935535430908
	]**
}

The last values are being altered by the Save Editor by a mathematical ratio!  Yes, the alteration is mathematically similar for every item at a ratio of 0.05434 of difference divided by original value.

Interesting, right?  Here's math proving this:

2.8039073944091799   -   2.651535749435425 = 0.1523716449737549
0.1523716449737549   ÷   2.8039073944091799 = **0.05434**260963025193136095224325762

16.4431095123291   -   15.54954719543457 = 0.89356231689453
0.89356231689453   ÷   16.4431095123291 = **0.05434**266044536977054753491497106

7.770935535430908   -   7.348642826080322 = 0.422292709350586
0.422292709350586   ÷   7.770935535430908 = **0.05434**258300370385793491722460737

Hopefully @goatfungus this helps you track down what is causing this issue.  I coded a couple of decades ago for a long time and realize these can be complex bugs to solve.  Maybe this will help you target the culprit.

Thank you for all you do.

**Comment by Devilin-Pixy** [comment] 2022-08-02 21:22
The issue is not actually how it stores the object data itself. After import this is still identical. The issue is actually the mismatch in the 'BaseVersion' value. This will only become clear after having loaded into the game and saving. The game uses this BaseVersion value to handle possible differences due to game updates and changes made, and will convert base data accordingly where needed.

What happens is the following. You export your base data, which would currently contain BaseVersion 6, and OriginalBaseVersion 6. After importing this base, the BaseVersion is now 3, while OriginalBaseVersion remains 6. So far almost all other data is correct (I will get to the 'almost' part in a bit). Now when you run the game, the game will see a BaseVersion 3 and applies changes to match the current BaseVersion 6 because the game now expects the base data to be outdated, and knows exactly what changes are supposed to be applied to still work correctly in the current version of the game. You will likely notice how your base ended up in a broken state for having incorrectly applied changes. You now save again at some point, and once back in the editor, you will see the actual changes that have been applied due to incorrect handling of the base version.

When a base is backed up, it should be an exact copy of the full base data, which also brings me to the following issue. The `Timestamp` values appear to be altered by the backup/restore process. Knowing how these values are used in-game, I can see this being an issue as well if not resulting in identical values. Logic and time based objects can actually break because of it.

I personally never used the backup / restore, as I create my own copy/pasta backups of the JSON instead of the backup restore format. I like to be able to actually read them standalone, as well as being able to use in other tools I often work with.

I am sure the mismatch between original and backup/restore can be easily fixed though. Meantime I suggest paying attention to those values, altering them as need be

**Comment by biffrapper** [comment] 2022-08-02 21:47
> The issue is not actually how it stores the object data itself. After import this is still identical. The issue is actually the mismatch in the `BaseVersion` value. This will only become clear after having loaded into the game and saving. The game uses this BaseVersion value to handle possible differences due to game updates and changes made, and will convert base data accordingly where needed.
> 
> What happens is the following. You export your base data, which would currently contain BaseVersion 6, and OriginalBaseVersion 6. After importing this base, the BaseVersion is now 3, while OriginalBaseVersion remains 6. So far almost all other data is correct (I will get to the 'almost' part in a bit). Now when you run the game, the game will see a BaseVersion 3 and applies changes to match the current BaseVersion 6 because the game now expects the base data to be outdated, and knows exactly what changes are supposed to be applied to still work correctly in the current version of the game. You will likely notice how your base ended up in a broken state for having incorrectly applied changes. You now save again at some point, and once back in the editor, you will see the actual changes that have been applied due to incorrect handling of the base version.
> 
> When a base is backed up, it should be an exact copy of the full base data, which also brings me to the following issue. Some of the `Timestamp` values appear to be altered by the backup/restore process. Knowing how these values are used in-game, I can see this being an issue as well if not resulting in identical values. Logic and time based objects can actually break because of it.
> 
> I personally never used the backup / restore, as I create my own copy/pasta backups of the JSON instead of the backup restore format. I like to be able to actually read them standalone, as well as being able to use in other tools I often work with.
> 
> I am sure the mismatch between original and backup/restore can be easily fixed though. Meantime I suggest paying attention to those values, altering them as need be

Interesting, so I change which version to what upon restore?  Make sure the restored version matches the original?

**Comment by Devilin-Pixy** [comment] 2022-08-03 01:29
If you want me to have a closer look, you could attach your exported file in a reply.

**Comment by biffrapper** [comment] 2022-08-03 05:46
Here's a couple  with the wires messed up on import:
[two bases.zip](https://github.com/goatfungus/NMSSaveEditor/files/9248290/two.bases.zip)

Thank you for your help.

**Comment by Devilin-Pixy** [comment] 2022-08-03 08:03
Had a quick look and you will have to edit the `BaseVersion` value from 3 to 6 in the raw JSON for both bases. That will fix all the wire issues.

I also came across another issue with 'COME_VISIT_Silver_Rig_Alpha'. It appears you have been using a mod that alters the amounts for mining, likely a multiplier on Extractors and Depots (`U_EXTRACTOR_S` and `U_SILO_S`), because of that, your base can not be uploaded in it's current state, because `UserData` values have become too large. The value should be a double-precision floating-point value (64-bit) and can therefor not be larger than (2^53)-1 = 9007199254740991. Your values have become too large, after which they have been saved as string literals. The server can not handle those thus failing to upload. You will however not notice, because the game is not giving any indication for failing to upload. Other players will just never see the base updated.

To fix these, you can try to empty all Extractors and Depots in-game after having removed the mod which caused this issue. Alternatively you can edit the values in Raw JSON. The UserData values will look like `"0x297E4900000000"`. Do note the quotation marks around it, and the `0x` prefix, indicating not only being hexadecimal, but also a string, while it should be a decimal value without the quotation marks.. They are easy to spot by doing a search for the IDs I mentioned. Your Extractors themselves may still be fine, as they often do not get an equally high value to get messed up. I would however suggest you edit these as well, editing all Silos and Extractors to have `UserData` value `0`.

Images of fixed bases, with the Cloaking Device removed to be able to see the wires. Mind you, these were imported into a Creative Save in a different location, just to check and have free power.

![275850_20220803092108_1](https://user-images.githubusercontent.com/7830771/182556409-22526a8e-7c71-4f1c-8c8d-a7abfbc438cf.png)

![275850_20220803093551_1](https://user-images.githubusercontent.com/7830771/182556575-7da29cb2-0306-4ef2-b228-87b49fffc9cb.png)

Feel free to ask questions and good luck.

**Comment by biffrapper** [comment] 2022-08-03 16:22
Ah yep, the silos are definitely bugged.  If I try and access them within the game it crashes every time--my only solution has been to access the extractors which still let me grab silver.  Very interesting those values were out of whack.  Thank you for noticing this.  I had sent Hello Games a bug report because I couldn't understand where the crashes were coming from.  The only mod I have ever used regularly is Beyond Base Building and another to make clouds match on planets.  I did try Gumsky's Base mod once, perhaps that is where the weirdness came from.

**Comment by biffrapper** [comment] 2022-08-03 17:59
Looks like changing those hex values to a base 10 integer fixed the storage tank problem!  You rock!

**Comment by Devilin-Pixy** [comment] 2022-08-03 23:46
That depends how large the value is/becomes. Let me explain what I know about the value for Extractors/Depots below:

## Info
UserData for Silo/Extractor = decimal value
Convert to hex (8 bytes, big endian) to understand better.
```
Byte(s):
1-4 Time Silo: max = 0015F900 (hex) = 1440000 (dec)
    Time Extractor: max = 00057E40 (hex) = 360000 (dec)
    Note: Silo is 4x Extractor.
5   Material: Concrete 00, Rust 01, Stone 02, Wood 03,
              Default 00 ?, None FF ?
6   Power Silo: always 00
    Power Extractor: Power 00, No power 02
7   ???: So far always 00
8   Colour: 00 - 0F
```
**_NOTE_**: The UserData field is using a double-precision floating-point value (64bit).
This means the max value = (2^53)-1 = `9007199254740991` !!!
Any value ≥ 2^53 (`9007199254740992`) will get stored as a literal string!
The UserData value 9007199254740992 would for example be converted to  "0x20000000000000", which is not uncommon (ie. JavaScript)

## Examples:
This makes a red/white wooden unpowered max filled Extractor:
`00057E40 03 02 00 08 = 00057E4003020008 (hex) = 1546188277022728 (dec)`
This makes a grey/black concrete/default powered max filled Silo:
`0015F900 00 00 00 0E = 0015F9000000000E (hex) = 6184752906240014 (dec)`
An empty white/orange concrete/default unpowered Extractor:
`000000 00 02 00 00 = 00000000020000 (hex) = 131072 (dec)`

**Comment by Devilin-Pixy** [comment] 2022-08-09 12:08
@goatfungus I have come across multiple reports now, where the BaseVersion requires fixing. Timestamp values also require to be an exact copy when exported, although less often resulting in an actual issue in-game, it can certainly mess things up.

Would love to see a fix for this when you have a moment.

**Comment by ukmerlin** [comment] 2022-08-19 13:17
I am now having the same problem. It also affects freighters with devices that dont actually need wiring. For example now there is a room teleport, but after using editor it no longer powers up. It is however, still functional.

**Comment by goatfungus** [comment] 2023-04-09 01:44
This should be fixed in the latest version.

**Closed by goatfungus** 2023-04-09 01:44 UTC
