### ISSUE TITLE
Ships are all very small (SOLVED)

### ISSUE THREAD

**Issue by GrumpyKoala1966** [goatfungus/NMSSaveEditor#723] opened 2023-02-25 05:24 UTC
Problem I'm having is after removing the "DISABLEMODS txt" file, ALL my ships are miniature in size, when I put back the "DISABLEMODS txt" file the ships are correct size.. Any help on this would be greatly appreciated..

*Issue is now Fixed*

**Comment by GrumpyKoala1966** [comment] 2023-02-25 05:54
![Screenshot (1)](https://user-images.githubusercontent.com/126310462/221341109-c52d8ccc-6188-4c4d-ab24-7aeaab1788a0.png)

**Comment by GrumpyKoala1966** [comment] 2023-02-25 06:42
I reinstalled the game and fixed the issue..

**Comment by Aducius** [comment] 2023-02-25 19:10
Same thing happened with my and was caused by one of my mods as most won't be compatible until updated. I also lost access to anomaly and Galaxy map as part of the same problem. If you' are using mods remove them one at a time to see which is the problem.

**Comment by GrumpyKoala1966** [comment] 2023-02-25 22:37
I took all Mods out and removed  "DISABLEMODS txt" but all ships were small still, so guessed adding back one at a time was pointless.. Think I'll just wait till all mods are fixed then give it a week and try again..

**Comment by BraveCaperCat2** [comment] 2023-03-20 19:30
please close this issue as it clutters up the open issues.

**Closed** 2023-04-06 23:10 UTC
