### ISSUE TITLE
Multitool List Doesn't Work After Deleting Multitool

### ISSUE THREAD

**Issue by handerson5991** [goatfungus/NMSSaveEditor#743] opened 2023-04-04 02:46 UTC
After going to the multitool tab and deleting excess multitools from the list, the multitool tab is greyed out and my current multitools do not work.

**Comment by goatfungus** [comment] 2023-04-06 23:11
I am unable to reproduce this issue on any of my saves. Can you please post a copy of your save file?

**Comment by goatfungus** [comment] 2023-04-24 00:48
Any remaining issues with multitool deletions should now be resolved in version 1.13.3.

**Closed by goatfungus** 2023-04-24 00:48 UTC
