### ISSUE TITLE
All Multitool edits are not saving.

### ISSUE THREAD

**Issue by Blockshaker246** [goatfungus/NMSSaveEditor#773] opened 2023-04-20 17:58 UTC
When ever I make any modifications to my multitool it doesn't stick no matter what. Aswell as I cannot import or export my multitools. I tried using the raw edit and nothing saved there either

**Comment by goatfungus** [comment] 2023-04-23 01:51
Duplicate of #772

**Closed by goatfungus** 2023-04-23 01:51 UTC
